global:
  resolve_timeout: 5m

route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alertas'
        send_resolved: true